name: benv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20230802.0
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - asttokens=2.4.1
  - attrs=23.1.0
  - blas=2.116
  - blas-devel=3.9.0
  - blinker=1.6.2
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.8.30
  - cachetools=5.3.3
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.2.2
  - cryptography=43.0.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cudatoolkit=11.8.0
  - cudnn=8.9.2.26
  - cupti=11.8.0
  - dataclasses=0.8
  - debugpy=1.6.7
  - decorator=5.1.1
  - emcee=3.1.6
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.2
  - ffmpeg=4.3
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.6.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-auth=2.29.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gtest=1.14.0
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=19.1.1
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - magma=2.7.1
  - markdown=3.4.1
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.3
  - nomkl=3.0
  - numba=0.60.0
  - numexpr=2.8.7
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - openblas=0.3.21
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.3.3
  - prompt-toolkit=3.0.47
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=5
  - pycparser=2.21
  - pygments=2.18.0
  - pyjwt=2.8.0
  - pyopenssl=24.2.1
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyzmq=25.1.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rsa=4.7.2
  - scipy=1.12.0
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.13.2
  - tbb=2021.8.0
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.14
  - torchaudio=2.3.0
  - torchtriton=2.3.1
  - torchvision=0.18.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - werkzeug=2.0.3
  - wheel=0.44.0
  - xz=5.4.6
  - yarl=1.11.0
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - alabaster==0.7.16
      - annotated-types==0.7.0
      - anyio==4.7.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - arviz==0.20.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - babel==2.16.0
      - baccoemu==2.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blosc2==2.7.1
      - camb==1.5.8
      - chainconsumer==1.1.2
      - classy==3.2.3
      - cloudpickle==3.1.0
      - configparser==7.1.0
      - cons==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==0.29.37
      - deepdish==0.3.7
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - docutils==0.20.1
      - dynesty==2.1.5
      - etuples==0.3.9
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - fqdn==1.5.1
      - gast==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - h11==0.14.0
      - h5netcdf==1.4.1
      - h5py==3.11.0
      - hdf5plugin==5.0.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - imagesize==1.4.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jax==0.6.0
      - jaxlib==0.6.0
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keras==2.15.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - logical-unification==0.4.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - minikanren==1.0.3
      - mistune==3.0.2
      - ml-dtypes==0.5.1
      - msgpack==1.1.0
      - multipledispatch==1.0.0
      - nbclient==0.10.2
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ndindex==1.8
      - nflows==0.14
      - notebook==7.3.1
      - notebook-shim==0.2.4
      - numpy==1.24.3
      - opt-einsum==3.3.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - patsy==0.5.6
      - progressbar2==4.5.0
      - prometheus-client==0.21.1
      - py-cpuinfo==9.0.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyfftw==0.14.0
      - pyknos==0.16.0
      - pylians==0.12
      - pymc==5.19.1
      - pyparsing==3.1.4
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytensor==2.26.4
      - python-json-logger==3.2.1
      - python-utils==3.8.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - sbi==0.23.2
      - scikit-learn==1.5.2
      - send2trash==1.8.3
      - sentry-sdk==2.18.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.6
      - sphinx==7.4.7
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - statsmodels==0.14.4
      - tables==3.10.1
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - toolz==1.0.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.0
      - uri-template==1.3.0
      - wandb==0.18.7
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - wrapt==1.14.1
      - xarray==2024.11.0
      - xarray-einstats==0.8.0
      - zuko==1.3.1
prefix: /home/kstoreyf/.conda/envs/benv
